### ISSUE TITLE
"Path" argument is undefined

### ISSUE THREAD

**Issue by Philmo3** [capacitor-community/electron#113]
Hi, I'm trying to add electron to my Ionic/angular app.

I did follow those instruction : https://capacitor-community.github.io/electron/#/ 
but i keep getting this error  when i do npx cap add @capacitor-community/electron: 

Adding Electron platform: The "path" argument must be of type string. Received undefined
(node:49760) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at Object.t [as doAdd] (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:6:240)
    at /Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:12:357
    at Object.g [as runTask] (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:2:1883)
    at o (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:12:311)
    at /Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:12:712
    at Object.parcelRequire.Focm../common (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:12:919)
    at f (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:1:468)
    at parcelRequire.FoEN (/Users/philippe/Desktop/my-repo/dercomobilefront/node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js:1:771)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:49760) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

this is my environment: 

node : 14.16.1
npm : 7.19.1

"@capacitor/core": "2.4.5",
"@capacitor/cli": "^2.4.5",

**Comment by IT-MikeS** [comment]
To use the current version of the electron platform you need to use version 3 or higher of capacitor
