### ISSUE TITLE
Reference to absoulte path in resulting .exe file -> unable to run on different system

### ISSUE THREAD

**Issue by digaus** [capacitor-community/electron#135]
**Describe the bug**

**To Reproduce**

1. Clone https://github.com/digaus/capacitor-plugin-demo
2. run `npm install`
3. run 'npm run build -- --prod'
4. run `npx cap sync @capacitor-community/electron`
5. run `npm run electron:build-windows` inside electron folder
6. Install .exe on a different System
7. Start .exe via Command Line Tool to see error

Following error occurs:
```
(node:12460) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\Users\User\Documents\Git\capacitor-plugin-demo\electron\node_modules\@digaus\file-server\electron\dist\plugin.js'
Require stack:
- C:\Users\digau\AppData\Local\Programs\capacitor-plugin-demo\resources\app.asar\node_modules\@capacitor-community\electron\dist\runtime\electron-plugins.js
- C:\Users\digau\AppData\Local\Programs\capacitor-plugin-demo\resources\app.asar\node_modules\@capacitor-community\electron\dist\core\util.js
- C:\Users\digau\AppData\Local\Programs\capacitor-plugin-demo\resources\app.asar\node_modules\@capacitor-community\electron\dist\core\index.js
- C:\Users\digau\AppData\Local\Programs\capacitor-plugin-demo\resources\app.asar\build\src\index.js
-
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\digau\AppData\Local\Programs\capacitor-plugin-demo\resources\app.asar\node_modules\@capacitor-community\electron\dist\runtime\electron-plugins.js:2:26)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
(Use `Capacitor App --trace-warnings ...` to show where the warning was created)
(node:12460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
 

**Expected behavior**
App should run normally and not reference an absolute path.

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by IT-MikeS** [comment]
This should have been using relatives but somehow I missed this in release, I'll have it corrected as soon as I have time this week 👍

**Comment by IT-MikeS** [comment]
Still working on this, it will be in `4.0.3`

**Comment by IT-MikeS** [comment]
I have resolved the paths issue, it will be in the next release along with plugin events
