### ISSUE TITLE
Error starting electron app on new projects (capacitor 6) : UnhandledPromiseRejection on /live-runner.js

### ISSUE THREAD

**Issue by hatsantos** [capacitor-community/electron#284]
**Describe the bug**
When starting a new ionic app and adding a electron capacitor plataform an erro happens when trying to start the electron app.
Yesterday Capacitor 6 was released. I don't know if it related to this new version.

```
npx cap open @capacitor-community/electron

ℹ Opening Electron platform: start 🚀
ℹ Opening Electron platform: building electron app
⠸ Opening Electron platform: running electron appError: undefined
✖ Opening Electron platform:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "
> TesteXPTO@1.0.0 electron:start-live
> node ./live-runner.js

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at D:\TesteXPTO\electron\live-runner.js:19:24
    at new Promise (<anonymous>)
    at runBuild (D:\TesteXPTO\electron\live-runner.js:18:10)
    at D:\TesteXPTO\electron\live-runner.js:72:9
    at Object.<anonymous> (D:\TesteXPTO\electron\live-runner.js:75:3)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v20.12.2
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.12.2
```

**To Reproduce**
ionic start > angular > XPTOapp > standalone
ionic build --prod
npm i @capacitor-community/electron
npx cap add @capacitor-community/electron
npx cap open @capacitor-community/electron

**Expected behavior**
Build should happen and app should start.

**Screenshots**

![image](https://github.com/capacitor-community/electron/assets/36542752/038cf2be-b5e4-462f-8446-97776eebafc1)

**Desktop (please complete the following information):**

```OS: Windows 11
 Version 22H2
 
 Ionic:
   Ionic CLI                     : 7.2.0 (C:\Users\hsantos\AppData\Local\pnpm\global\5\.pnpm\@ionic+cli@7.2.0\node_modules\@ionic\cli)        
   Ionic Framework               : @ionic/angular 7.8.4
   @angular-devkit/build-angular : 17.3.4
   @angular-devkit/schematics    : 17.3.4
   @angular/cli                  : 17.3.4
   @ionic/angular-toolkit        : 11.0.1

Capacitor:
   Capacitor CLI      : 6.0.0
   @capacitor/android : 6.0.0
   @capacitor/core    : 6.0.0
   @capacitor/ios     : not installed

Utility:
   cordova-res : not installed globally
   native-run  : 2.0.1

System:
   NodeJS : v20.12.2 (C:\Program Files\nodejs\node.exe)
   npm    : 10.5.0
 ```

**Comment by hatsantos** [comment]
I think it's related with the node version... The latest LTS seems to crash the build.

**Comment by satheshsat** [comment]
I am also getting same error. My node version is Node.js v18.20.2

**Comment by jduerr** [comment]
Experiencing the exact same error. 
Did anybody find a working solution?

**Comment by ethrydevelops** [comment]
Same error, node v20.12.2

**Comment by hatsantos** [comment]
I had to downgrade to node version 18.19.0 to make it work.

**Comment by TruongHaiDang** [comment]
> I had to downgrade to node version 18.19.0 to make it work.

Thanks you. It work for me.

**Comment by Frooger** [comment]
you can fix it by change line 19 in live-runner.js
from
`let tempChild = cp.spawn(npmCmd, ['run', 'build']);`
to
`let tempChild = cp.spawn(npmCmd, ['run', 'build'], {shell: true});`

https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

**Comment by rameezusmani** [comment]
> you can fix it by change line 19 in live-runner.js from `let tempChild = cp.spawn(npmCmd, ['run', 'build']);` to `let tempChild = cp.spawn(npmCmd, ['run', 'build'], {shell: true});`
> 
> https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

thank you so much....but for other devs I want to add more from my experience. Today I worked first time with **_capacitor-community/electron_** on packaging my Ionic/Capacitor app with Electron. With **_Nodejs 20.x_** everything was working fine but I updated to **_Nodejs 22.x_** and suddenly started facing this error. 
Adding **{shell: true}** fixed the issue of **_npx cap open electron_** but when I was packaging my electron app into a windows executable I was getting different errors because of newer Nodejs version.

So here is what I have done to fix everything (inside **_electron_** folder):
1) As **Frooger** mentioned...add **{shell: true}** in **_live-runner.js_** file
2) Update all your **package.json** dependencies to their latest version...but _**NOT**_ **_electron-unhandled_**.
3) If your app make HTTP/HTTPS calls...then you will face **Content-Security-Policy** errors...no matter what you do in **index.html** it will be overwritten...the **Content-Security-Policy** must be changed in **src/setup.ts** file under _**setupContentSecurityPolicy**_ function:
```
callback({
       responseHeaders: {
         ...details.responseHeaders,
         'Content-Security-Policy': [
           electronIsDev
             ? `default-src ${customScheme}://* 'unsafe-inline' devtools://* 'unsafe-eval' data:`
             : `default-src ${customScheme}://* 'unsafe-inline' data:`,
         ],
       },
});
```
