### ISSUE TITLE
code: 'ERR_UNHANDLED_REJECTION' 

### ISSUE THREAD

**Issue by olverwall** [capacitor-community/electron#295]
I have tried with different versions of node 22.7 and 20.14 and 18.20
npx cap open @capacitor-community/electron
i Opening Electron platform: start 🚀
i Opening Electron platform: building electron app
\ Opening Electron platform: running electron appError: undefined
× Opening Electron platform:
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "
> Admin Bluebell@1.0.0 electron:start-live
> node ./live-runner.js

node:internal/child_process:421
    throw new ErrnoException(err, 'spawn');
          ^

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:761:9)
    at C:\Users\antonio.olvera\Desktop\adminBluebellCode\electron\live-runner.js:19:24
    at new Promise (<anonymous>)
    at runBuild (C:\Users\antonio.olvera\Desktop\adminBluebellCode\electron\live-runner.js:18:10)
    at C:\Users\antonio.olvera\Desktop\adminBluebellCode\electron\live-runner.js:72:9
    at Object.<anonymous> (C:\Users\antonio.olvera\Desktop\adminBluebellCode\electron\live-runner.js:75:3)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}

Node.js v20.14.0
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.14.0

**Comment by Frooger** [comment]
you can fix it by change line 19 in live-runner.js
from
`let tempChild = cp.spawn(npmCmd, ['run', 'build']);`
to
`let tempChild = cp.spawn(npmCmd, ['run', 'build'], {shell: true});`

https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2

**Comment by themalikx** [comment]
@Frooger It works, Thank you. 
Can you explain the reason, why it happened?

**Comment by Frooger** [comment]
Read the blog post above ☝️
Basically node.js restricted the use of bash scripts because of security purpose.

The line 19 Frome above is used by electron for execute build pipeline from npm
