### ISSUE TITLE
Cannot find index.js in built MacOS app

### ISSUE THREAD

**Issue by darkfrog26** [capacitor-community/electron#72]
**Describe the bug**
Error at application startup

**To Reproduce**

1. Build and run the Electron app on MacOS, shows alert with:

`Uncaught Exception:
Error: Cannot find module ```
/Users/mhicks/projects/clients/courio/courio/capacitor/electron/out/make/zip/darwin/x64/Courio.app/Contents/Resources/app/build/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Object.<anonymous> (electron/js2c/browser_init.js:185:3470)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:185:3714)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compileForInternalLoader (internal/bootstrap/loaders.js:277:7)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:219:10)
    at loadNativeModule (internal/modules/cjs/helpers.js:24:9)
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**

- OS: MacOS

**Comment by IT-MikeS** [comment]
What version of MacOS is this happening on?

**Comment by darkfrog26** [comment]
10.15.7

**Comment by IT-MikeS** [comment]
I have tested this a few times, and had a few other people I know try this without being able to reproduce. I may be an issue with your local system/project setup, give it a shot with a very generic starter app and see if you still have issues
